if(m_online.status!='0'){document.write('<style type="text/css" media="all">');document.write("@import url("+m_online.css+");");document.write("</style>");var LorR="0";$(function(){if(m_online.status!="1"){LorR=document.body.clientWidth-161}});var biaoshi=0;var QQbiaoshi=0;var WWbiaoshi=0;if(m_online.status=='1'){document.write('<div id="divStayTopLeftOnline" style="left:'+LorR+'px;" >');}
else
if(m_online.status=='2'){document.write('<div id="divStayTopLeftOnline" style="right:'+LorR+'px;" >');}
document.write('<table cellSpacing="0" cellPadding="0"  border="0" id="qqtabOnline">');document.write("<tr>");if(m_online.status=="1"){}
document.write('<td class="topline"><span>&gt;&gt;</span> 在线咨询</td>');if(m_online.status!="1"){document.write("<td></td>")}
document.write("</tr>");document.write("<tr>");if(m_online.status=="1"){document.write('<div class="rs_lineBtn" onclick="onlineHidden()"><i></i>在线客服<b>&lt;&lt;</b></div>')}
document.write('<td class="contentOn" align="center">');var m_type=m_online.type[0];var ob="<div class=\"content_xiahuax\" > </div>";for(var i=0;i<m_online.type.length;i++){var typ=m_online.type[i];if(m_type!=typ)
{document.write(ob);console.log(ob);}
switch(typ){case "0":document.write('<div class="content_action" >');if(QQbiaoshi==0){document.write('<h4>QQ客服</h4>');QQbiaoshi=1;}
document.write("<a target=blank href='tencent://message/?uin="+m_online.value[i]+"&Site=abc&Menu=yes'><img src='images/online_qqIcon01.png'/></a>");document.write("</div>");break;case "1":document.write('<div class="content_action" >');document.write("<a href='msnim:chat?contact="+m_online.value[i]+"' target=blank><img src='https://china.jqw.com/images/msn.gif' border=0 /></a>");document.write("</div>");break;case "2":document.write('<div class="content_action" >');document.write('<a href="skype:'+m_online.value[i]+'?call"><img src="https://download.skype.com/share/skypebuttons/buttons/call_blue_white_124x52.png" width="100" alt="Skype Me?!" /></a>');document.write("</div>");break;case "3":document.write('<div class="content_action" >');document.write("<a target='_blank' href='https://wpa.qq.com/msgrd?V=1&Uin="+m_online.value[i]+"&Exe=TT&Site=Simplelife&Menu=yes'>");document.write("<img border=0 src='https://wpa.qq.com/pa?p=4:"+m_online.value[i]+":3' border=0 />");document.write("</a>");document.write("</div>");break;case "4":document.write('<div class="content_action" >');document.write('<a href="https://edit.yahoo.com/config/send_webmesg?.target='+m_online.value[i]+'&.src=pg" target="_blank">');document.write('<img border=0   src="http://opi.yahoo.com/online?u='+m_online.value[i]+'&m_online=g&t=1&l=cn"/></a>');document.write("</div>");break;case "5":document.write('<div class="content_action" >');if(WWbiaoshi==0){document.write('<h4>阿里旺旺</h4>');WWbiaoshi=1;}
document.write('<a href="https://amos.im.alisoft.com/msg.aw?v=2&uid='+m_online.value[i]+'&site=cntaobao&s=1&charset=gb2312" target="_blank">');document.write('<img src="images/online_wwIcon.png"/></a>');document.write("</div>");break;case "6":document.write('<div class="content_action" >');document.write('<a href="https://amos.im.alisoft.com/msg.aw?v=2&uid='+m_online.value[i]+'&site=cnalichn&s=1&charset=gb2312" target="_blank">');document.write('<img src="images/online_wwIcon.png"/></a>');document.write("</div>");break;case "7":document.write('<div class="content_action" >');document.write('<div class="freebg">Free Phone</div>');document.write('<div class="free_phone">'+m_online.value[i]+"</div>");document.write("</div>");break;case "8":document.write('<div class="content_action" >');document.write('<div class="freebg">Free Phone</div>');document.write('<div class="free_phone">'+m_online.value[i]+"</div>");document.write("</div>");break;case "9":var qrurl=m_online.value[i];if(qrurl.indexOf("http://img")<0){var qrurl="https://qrcode.jqw.com/qrcode.aspx?web="+qrurl+"&size=3";}
if(m_online.QR!="undefined"&&m_online.QR!=null){qrurl=m_online.QR}
var qr_ttle="二维码";if(qrurl!="")
{var arr=new Array();arr=qrurl.split(',');if(arr.length>1)
{qr_ttle=arr[1];qrurl=arr[0];}}
document.write('<div class="content_action"><h4>'+qr_ttle+'</h4><img src="'+qrurl+'" width="100px"/></div>');break;case "10":document.write('<div class="content_action" >');if(biaoshi==0){console.log(12);document.write('<h4>服务热线</h4>');biaoshi=1;}
document.write('<div class="free_phone"><p>'+m_online.value[i]+"</p></div>");document.write("</div>");break;case "11":document.write('<div class="content_action" >');document.write('<h4>微信号</h4>');document.write('<div class="free_phone"><p>'+m_online.value[i]+"</p></div>");document.write("</div>");case "12":document.write('<script src="'+m_online.value[i]+'"></script>');default:break}
m_type=m_online.type[i];}
document.write("</td>");if(m_online.status!="1"){document.write('<div class="rs_lineBtn" onclick="onlineHidden()"><i></i>在线客服<b>&lt;&lt;</b></div>')}
document.write("</tr>");document.write("<tr>");document.write("<td><a href='javascript:;' rel='nofollow' class='goTop'><img src='images/gotop.png'>返回顶部</a></td>");document.write("</tr>");document.write("</table>");document.write("</div>");$(function(){$("#divStayTopLeftOnline").css("z-index","99999999");$(".rs_lineBtn").hide();$("#qqtabOnline").show();var thisBox=$('#divStayTopLeftOnline');var defaultTop=thisBox.offset().top;var slide_min=$('#divStayTopLeftOnline .rs_lineBtn');var slide_box=$('#divStayTopLeftOnline #qqtabOnline');var closed=$('#divStayTopLeftOnline .topline');slide_min.on('click',function(){$(this).hide();slide_box.show();});closed.on('click',function(){slide_box.hide().hide();slide_min.show();});$(window).on('scroll',function(){scro();});$(window).onload=scro();function scro(){var offsetTop=(defaultTop+$(window).scrollTop()+50)+'px';thisBox.animate({top:offsetTop},{duration:600,queue:false});}
goTop_nav();$(window).scroll(function(){goTop_nav();});$(".goTop").click(function(){$("html,body").animate({scrollTop:0},400);});});function goTop_nav(){var scrollTop=parseInt($(this).scrollTop());if(scrollTop>400){$(".goTop").css({"display":"block"});}else{$(".goTop").css({"display":"none"});}};}